version: "3"
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: "calendar"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password123"
      TZ: 'UTC'
      PGTZ: 'UTC'
    ports:
      - "5432:5432"