version: "3"
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: "calendar"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password123"
      TZ: 'UTC'
      PGTZ: 'UTC'
    volumes:
      - ../migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    volumes:
      - ./rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
    ports:
      - "5672:5672"
      - "15672:15672"