logger:
  level: 1
  timeformat: 2006-01-02T15:04:05Z07:00
storage:
  mode: in-memory
  dsn: postgres://user:password123@localhost:5432/calendar
httpserver:
  host:
  port: 8888
grpcserver:
  host:
  port: 9999